name: CI

on: [push, pull_request, workflow_dispatch]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - uses: cypress-io/github-action@v2
        with:
          working-directory: "example"
          # install-command: echo "skip cypress install"
          # command: echo "skip cypress run"
          runTests: false
          browser: chrome
          headless: true

      - name: Run tests
        run: ./script/test
